### ISSUE TITLE
Absolute links in openapi.yml $ref

### ISSUE THREAD

**Issue by sophieherrmann** [radiantearth/stac-api-spec#102]
Hi Devs!

Would it be possible to use only absolute links in the `openapi.yml` $refs? 

e.g. use `$ref: "https://raw.githubusercontent.com/radiantearth/stac-api-spec/v1.0.0-beta.1/core/commons.yaml#/components/schemas/item"`  
instead of `$ref: '../core/commons.yaml#/components/schemas/collection'`
example taken from [here](https://github.com/radiantearth/stac-api-spec/blob/v1.0.0-beta.1/ogcapi-features/openapi.yaml#L282)

We are getting the references recursively to build up a complete openapi.yml in our code. So absolute references would be great for us.

**Comment by m-mohr** [comment]
Hi @sophieherrmann,

maintenance with absolute links is very hard as in-between releases those links don't update and thus makes the spec writing process harder for us. Fortunately, there are likely ways around it:
- We publish dereferenced versions, e.g. https://api.stacspec.org/v1.0.0-beta.1/ogcapi-features/openapi.yaml for STAC API Core + OGC API Features
- You can use a tool such as https://github.com/APIDevTools/json-schema-ref-parser to get rid of the relative references (it's also used to generate the dereferenced version above)

Does this help?

**Comment by sophieherrmann** [comment]
Thanks a lot! The links help very much.
