### ISSUE TITLE
Migrate ItemCollection definition to stac-extension extension

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#110]
Migrate ItemCollection definition to stac-extension extension

**Comment by matthewhanson** [comment]
@philvarner I put up an initial version of item-collection pulling from the past definition, but the JSON schema has not been updated yet. I think it should be done from scratch following the newer schema style.  cc @m-mohr

**Comment by philvarner** [comment]
great, I'll take a look at that

**Comment by m-mohr** [comment]
I think at some point we decided to not move it to the extensions, right? @matthewhanson said he wants to delete https://github.com/stac-extensions/item-collection again... can't remember the reasons though.
