### ISSUE TITLE
Change root endpoint (/) the be a Catalog, rather than a Collection or a Catalog

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#111]
Right now, the text spec just says that it's JSON, but the OpenAPI definition says it can be either a Catalog or a Collection.  I think it would be cleaner if this was only a Catalog. Allowing it to be either makes it a bit more complex to interact with, and I feel that generally an API will be built over a Catalog rather than a single Collection.

**Comment by cholmes** [comment]
+1 - makes sense to me. Would be weird if it's just a collection, and if an implementor wants to do just have one collection they can just put a catalog that links to one collection.

**Comment by matthewhanson** [comment]
Agree as well, Catalog requirement makes sense.

**Comment by philvarner** [comment]
I'm going to add this to the description of Catalog in stac-spec and put a PR in to update this repo.
