### ISSUE TITLE
Make item search extensions more prominent

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#113]
Recently, I was quite often asked whether the search endpoints aren't a bit limited. I was confused but later found out people just don't always see the extensions at the end of the page. We need to mention them more prominent, because people seem to miss them since we reorganized the repo recently. People are especially asking about the query extension.

**Comment by cholmes** [comment]
That seems reasonable. For the next release we hopefully bring in OGC Filter - maybe we put that in its own 'top level' folder. Or we could do like 'advanced querying' and include context, sort, fields. Hrm, maybe we could just 'rebrand' fragments to that, as I think we agreed we're taking 'itemcollection' out.

**Comment by m-mohr** [comment]
It could be as easy as having a TOC at the top of the pages or something similar,

**Comment by cholmes** [comment]
Ah, good point.
