### ISSUE TITLE
Update rendered versions on stacspec.org

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#12]
Update
* https://stacspec.org/STAC-api.html
* https://stacspec.org/STAC-ext-api.html

to point to this repo once STAC 1.0 is released.

**Comment by cholmes** [comment]
@matthewhanson - I think you said you could take this one? 

I believe we decided that we'd make this so it'd automatically publish the openapi docs to stacspec.org (like how we do with json schemas, but published to an api directory with folders for each api version), and we'd get rid of the generated version in the repo.

**Comment by m-mohr** [comment]
We should not forget to add a redirect from the current files to the new locations.

**Comment by cholmes** [comment]
I'm not sure if an automatic redirect makes sense until we have the full combined rendered html, since it'd be weird to redirect to just the core spec. But I think we should update the existing one with a note at the top that points people at the new repo / release.

**Comment by m-mohr** [comment]
Okay, that makes sense. I guess we should go through the repos and change the old links then...
