### ISSUE TITLE
Subscribe to data changes?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#120]
We have the use case that we need to get notified of new items that have been added as we then need to run processing again. This could surely be broadened up to something that also notifies about changes and removals. User should specify search criteria when they set up the subscription.

So we are wondering whether an API extension that lets us do so would be of interest to others, too? This should include restricting the subscription to certain filters such as time and space, but could in principle be anything that you can express with CQL. This could be modeled as an extension so Item Search where you simply send the same requests to an endpoint, but instead of returning results, it creates a subscription that then can notify you via different types of services (e-mail, push notifications, HTTP callbacks, ...). 

Obviously, STAC is using HTTP and as such has a focus on pulling information and not pushing them, but it still seems to be an obvious use case that arises from a catalog service.

I'm aware that some catalogs have set up SNS topics on AWS, but that, unfortunately, works only with AWS.

**Comment by philvarner** [comment]
Moved: 

- https://github.com/stac-api-extensions/incubator/issues/1
