### ISSUE TITLE
Rely on rel=search for Item Search path instead of requiring it to be the fixed path "/search"

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#122]
Currently, we require that the Item Search endpoint be `/search` and that the root endpoint have a Link with rel `search` that points to the endpoint. 

I propose we change this so that:
1) the root endpoint entity have a Link with rel `search` that points to the Item Search endpoint
2) the path for the Item Search endpoint **not** be required to be `/search`, and that it up to the implementer what the name is. (we could still recommend it be something)

There are a couple main reasons for this change:

1) `/search` is named in a *action resource* style, rather than the more RESTful *entity resource* style. An entity resource name for this endpoint can be `/items`, since it returns the same entity type (ItemCollection) as returned by `/collections/{cid}/items`. In fact, we should recommend that implementers use `/items` for the path, but, they can still use `/search` if they want.
2) We want to encourage hypermedia-oriented discovery and navigation of the API, and requiring the endpoint have a fixed name isn't necessary when clients should only need to know the root endpoint, to which they can use the rel=search link to discover the search endpoint. 

The effect on backwards-compatibility for this is limited to clients who are not using the root endpoint rel=search link, which they should be, and will be an easy fix for those that aren't.

**Comment by matthewhanson** [comment]
Not sure why this was closed - has it been decided to not allow anything other than /search?

I actually thought that it was already like this, pystac-client uses the links to determine what the search endpoint is.

**Comment by philvarner** [comment]
Nothing was decided. I closed it because there weren't any other comments, and I thought it was just another one of my hare-brained ideas.

**Comment by philvarner** [comment]
One other consideration is how this will align with the OGC API Search spec https://github.com/opengeospatial/ogcapi-features/blob/3623485b918727dbe174af6a2aa446b8dd1f620d/proposals/search/README.md
Note that this says Part 5, but Part 5 is actually going to be the OpenAPI definition, so it will have to be named another Part.

I don't like the definition of fixed paths when hypermedia can be used instead, but I also would rather conform to the OGC API conventions rather than do something else just because it's more RESTful/HATEOAS. 🤷🏻

**Comment by philvarner** [comment]
I thought about this more and am closing. I think endpoint discovery through links and not requiring a fixed path is the best design, but this is not the OGC convention. In all the OGC endpoints I've seen (except service-desc and service-doc), the endpoint is a fixed value.
