### ISSUE TITLE
Item search -- why does "ids" deactivate other filters?

### ISSUE THREAD

**Issue by jisantuc** [radiantearth/stac-api-spec#124]
In item search, the note on the `ids` query says "All other filter parameters that further restrict the number of search results (except `next` and `limit`) are ignored." Why is this the case?

I'm trying to figure out what power this adds -- a user who wanted to filter by ids only could already provide just the `ids` parameter, so I think it adds implementation complexity ("interpret combinations of filters as `and` except in this one special case") without enabling any new interactions.

This specification directly contradicted both my expectations in implementing search in Franklin and a user's expectation of specifying multiple filters https://github.com/azavea/franklin/issues/707#issuecomment-832083568

**Comment by philvarner** [comment]
I agree with this assessment. I originally implemented it incorrectly in the same way in Earth OnDemand, and never got around to fixing it (which, is risky, since someone might be relying on this behavior!). 

I was about to say I'd be surprised if anyone else was doing this according to spec, but it looks like stac-fastapi is doing so.

**Comment by philvarner** [comment]
Since @geospatial-jeff gave a thumbs-up, I'll go ahead and create a PR to change this for beta.2.

**Comment by matthewhanson** [comment]
Earth-search (stac-server) implements it as per the spec. 
I agree it's unnecessary to have the restriction.

**Comment by jisantuc** [comment]
@philvarner I went ahead and opened a PR a second ago -- there aren't examples with `ids`, so no changes were required outside of updating the description in openapi and the README

**Comment by jisantuc** [comment]
Woops this should have been closed with that PR
