### ISSUE TITLE
Item search -- why is there a default limit and a maximum?

### ISSUE THREAD

**Issue by jisantuc** [radiantearth/stac-api-spec#126]
I'm confused about why `default` and `maximum` are specified here: https://github.com/radiantearth/stac-api-spec/blob/dev/item-search/openapi.yaml#L200-L204

Specifying that the max value for limit is 10k in the spec restricts implementers from making appropriate choices for their servers. The same is true for the default. Requiring a default / maximum in the specification forces compliance beyond what's necessary for clients to know what they're getting.

**Comment by jisantuc** [comment]
Do we need to inherit it? If the spec doesn't really have an opinion, would you object to removing it?

**Comment by m-mohr** [comment]
In OGC API - Features I'd say we should inherit, but as you were referring to Item Search I think we could drop it OR add some language around it that explains it.
