### ISSUE TITLE
Transactions evolution

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#14]
There's a PR for changing the Transactions extension some - https://github.com/radiantearth/stac-spec/pull/634 but no issue to move. Probably need to redo the PR to be against this repo.

Proposed Changes:
Rename Transaction Extension to CRUD Extension since bulk operations are not transactional. They are equivalent to WFS batch operations, i.e. individual operations succeed or fail independently.
ETags to support optimistic locking for PUT, PATCH, and DELETE are always optional.
Add spec for bulk POST and DELETE within a collection.
Consistently use the term item when appropriate instead of feature.

It looks like OGC API - Features has made progress on their transaction extension, so perhaps we should align with theirs, see https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/transactions/simple/standard/clause_6_simpletx.adoc

https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/transactions/simple/

cc 	@gsf-sellis

**Comment by m-mohr** [comment]
See also the draft doc for OGC API - Features - P4 -Simple Transactions
https://t.co/YQEUDKL4RV

**Comment by cholmes** [comment]
Closing in favor of #33 - and if we want changes like etags then we should aim to do it at that level (could also start those additions in STAC, but should aim to get it into core)
