### ISSUE TITLE
Remove stac_version and stac_extensions from ItemCollection?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#141]
I think we should remove the required fields stac_version and stac_extensions from ItemCollection.
stac_version contains the stac-spec version in all other specs, but ItemCollection is not even defined in stac-spec. So what to include there? I think the ItemCollection schema in API responses is implicitly clear through the Conformance classes and thus should be handled similarly to for example the "Collection Collection" (i.e. /collections) for example. There's also no stac_version etc. included.

**Comment by cholmes** [comment]
Agreed. And to be clear, we'll have a stac_version in each of the Items that is in the ItemCollection, right?

**Comment by m-mohr** [comment]
Sure.

**Comment by emmanuelmathot** [comment]
Agreed. However to ensure a proper crawling/validation of a catalog tree out of a STAC API, this is necessary to have the related json schemas. Do we consider the GeoJson (FeatureCollection)[https://datatracker.ietf.org/doc/html/rfc7946#section-3.3] the baseline for validation?

**Comment by m-mohr** [comment]
We could provide a GeoJSON-based JSON Schema linking to the stac-spec Item Schema in stac-api-spec, but STAC API validation would usually be done through OpenAPI like we have for the other endpoints. I mean there's also no JSON Schema for /collections for example...
