### ISSUE TITLE
Align Filters with OGC API - Features

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#15]
OGC API - Features is working on CQL, see https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/cql

We should work to align with them, getting to a subset that works well for STAC and helping evolve that spec to work for us. Or else be very sure we can't align and have solid reasons for going in another direction.

**Comment by m-mohr** [comment]
See also the draft doc for OGC API - Features - P3 - Common Query Language (https://t.co/oBwtHMMJRC

**Comment by cholmes** [comment]
Whoops, duplicate of #32
