### ISSUE TITLE
Clarify how rel=items is implemented in the STAC API spec

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-api-spec#161]
Collections that are returned from an API do not have any `rel=item` links, but have `rel=items`. The meaning of this reltype is inherited by the [OGC API: Features spec](https://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_link_relations). However a STAC user trying to understand the meaning of `rel=items` vs `rel=item` has to dig in a few different places to piece together how those two link types (don't) relate, and that `rel=items` isn't part of core STAC but instead the STAC API by way of oafeat. 

This topic could use some documentation in the STAC API spec, and potentially in the Collection spec, to make clear where `rel=items` comes from.

See [this Gitter conversation](https://gitter.im/SpatioTemporal-Asset-Catalog/Lobby?at=60d44c9e24f0ae2a242538cc) for a discussion about this topic.

**Comment by cholmes** [comment]
My comments on #159 are also related to this - I think we also need to get more clear on how things should be done in API specs.

**Comment by matthewhanson** [comment]
Does there need to be an additional conformance class for this?  Or perhaps that's already handled by the OAF conformance. It just doesn't define a `rel=items` link type.
There's a conformance class for item-search, but that only applies to the `search`.

**Comment by philvarner** [comment]
I added some clarifying language here: https://github.com/radiantearth/stac-api-spec/pull/172

A better place for this will be when we add the Collections conformance class https://github.com/radiantearth/stac-api-spec/issues/134
