### ISSUE TITLE
should bbox parameter tolerate whitespace?

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#164]
Should `bbox=100.0, 0.0, 105.0, 1.0` be treated the same as `bbox=100.0,0.0,105.0,1.0`?

**Comment by m-mohr** [comment]
IMHO should be not allowed. Whitespaces in URLs are a pain...

**Comment by matthewhanson** [comment]
Agree, all array parameters (bbox, ids, collections) when provided via GET should not have any whitespace

**Comment by philvarner** [comment]
I'll add something in the spec and validator for this.
