### ISSUE TITLE
OAFeat rendered OpenAPI document v1.0.0-beta.2 displays an error

### ISSUE THREAD

**Issue by alainbodiguel** [radiantearth/stac-api-spec#165]
When accessing https://api.stacspec.org/v1.0.0-beta.2/ogcapi-features/ an error is displayed instead of the actual API description.

**Comment by philvarner** [comment]
@m-mohr you mentioned this right before the mtg ended

**Comment by philvarner** [comment]
@alainbodiguel thanks for filing this issue. After a few hours of working on it, I finally fixed the build and I think we'll be able to publish a new version of this.
