### ISSUE TITLE
intersects in GET /search

### ISSUE THREAD

**Issue by aznan2** [radiantearth/stac-api-spec#166]
The spec currently allows all parameters as a query string in a GET request or as JSON properties in a POST request. However, it seems that parameter serialization behavior is undefined for nested objects and arrays. 

How would this query be represented in a GET request?

```
{
  "intersects": {
    "type": "LineString",
    "coordinates": [
      [1, 1, 1]
      [2, 2, 2]
    ]
  }
}
``` 

This needs to be clearly defined or dropped.

**Comment by philvarner** [comment]
for intersects, the parameter is a string of GeoJSON, e.g.,

`/search?intersects={"type": "LineString", "coordinates": [ [1, 1, 1] [2, 2, 2] ] }`

with appropriate URL encoding applied to the intersects value.

**Comment by aznan2** [comment]
Ah, okay. Thanks for clearing that up!
