### ISSUE TITLE
Item Search - align required endpoints

### ISSUE THREAD

**Issue by aznan2** [radiantearth/stac-api-spec#167]
In the current README.md for Item Search it says:

> Implementing GET /search is required, POST /search is optional, but recommended.

At the same time, the openapi.yaml says for GET:

> This method is optional, but you MUST implement `POST /search` if you want to implement this method.

And for POST:

> This method is mandatory to implement if `GET /search` is implemented.

Which of these are true?

**Comment by philvarner** [comment]
`Implementing GET /search is required, POST /search is optional, but recommended.` is correct
