### ISSUE TITLE
Filter Ext: pycql and pygeofilter

### ISSUE THREAD

**Issue by constantinius** [radiantearth/stac-api-spec#186]
Just some notes here: in the filter extension, pycql and pygeofilter are mentioned. pycql is discontinued and pygeofilter is it's successor.
Also ECQL is the old CQL standard defined in some old OGC CSW spec, not a superset of the current CQL Text standard from OGC API Features. (Which will be implemented soon).

**Comment by philvarner** [comment]
Thanks, I'll make those updates.
