### ISSUE TITLE
Add "queryables" from OGC APIs

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#19]
Add the queryables features that OGC APIs (will) have. It defines the fields you can search on. It also seems useful for STAC API as discussed in https://github.com/radiantearth/stac-spec/issues/757#issuecomment-613640331

**Comment by m-mohr** [comment]
See also the draft doc for OGC API - Features - P3 - Common Query Language (https://t.co/oBwtHMMJRC

**Comment by matthewhanson** [comment]
Closing this as it's part of CQL which we will adopt once it's in OGC API.
