### ISSUE TITLE
OGC API conformance classes for Filter

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#194]
To improve compatibility, I'd propose to also list the OGC API conformance classes for the filter extensions whenever one of our conformance classes fully includes one of theirs or if a set of our conformance classes map one of their conformance classes. This would help to make out ecosystem align more. I don't see a good reason (yet?) why we stick solely with custom conformance classes instead of mapping them whenever possible. In general, it would be great to have a list of how our conformance classes relate to the OGC API conformance classes.

**Comment by philvarner** [comment]
OGC API conformance classes draft updated https://github.com/opengeospatial/ogcapi-features/commit/29ab01f447d44b3d843704a31258b02be82ecdfe

**Comment by philvarner** [comment]
I ended up not adding a table, since we're not aligned except for one minor difference

**Comment by m-mohr** [comment]
I don't understand. My point was to add OGC API conformance URIs and I don't see them in the PR. Also, why are we completely misaligned with them?

**Comment by philvarner** [comment]
I typed that too quickly -- I meant to say were **are** aligned except for one minor difference (upper/lower function in Advanced Comparison Operators). All of the conformance classes are named the same, and all of the URIs have the same ending.

**Comment by m-mohr** [comment]
Ah, okay. But wouldn't it be more clear to just list them so that people can copy&paste them easily instead of have them search for them? From the docs it doesn't become directly clear how to "convert" the URLs (to get OGC API compliant), too, right?
