### ISSUE TITLE
STAC API - Collections feedback

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#195]
Some feedback for the STAC API - Collections: 
1. The Maturity says "Pilot", which is a bit weird as there's no implementation for that conformance class yet (I think) and no OpenAPI document is available. I guess it should be "Proposal" instead?
2. As this is explicitly for STAC API - Collections, I think the data relation type should be required. There are no child links in OAFeat defined as far as I know, so I think the child relation should just not be listed or at least not be listed in the main table of relation types to implement. (Just seeing that it's required at the end in the Conformance section, but listed as "should" in the table. That conflicts a bit...)
3. Is a root relation type really useful in the root "catalog" / landing page? It seems to mirror self 1:1.
4. The items relation type should probably point to the full OGC API Features extension so that people see what "items" actually should be. 
5. Isn't the list of endpoints missing the `/` endpoint (and potentially an indication on the API (e.g. `/api`) endpoint)?
6. I'd propose to put the example into a separate file like we do it in most other cases, too. Then it could also be extended a bit with an additional collection in the current example and an additional example for the landing page.
7. The relation types mentioned in the example text (canonical, alternate representation) are not listed in any of the tables.
8. The "NOTE: When this aligns with OGC API - Common it will also need to add it to the /conformance endpoint." should probably be phrased differently. It basically also applies to Features and for better OGC API compliance I'd actually add it to the top list of relation types. I don't see this is not (directly) inherited from OGC APIs while the other parts are, e.g. the API doc endpoint(s).

**Comment by philvarner** [comment]
>     1. The Maturity says "Pilot", which is a bit weird as there's no implementation for that conformance class yet (I think) and no OpenAPI document is available. I guess it should be "Proposal" instead?

I put it in pilot because it's just a subset of `STAC API - Features`. Any impl that already supports that class can just add this conformance class.

> 2. As this is explicitly for STAC API - Collections, I think the data relation type should be required. There are no child links in OAFeat defined as far as I know, so I think the child relation should just not be listed or at least not be listed in the main table of relation types to implement. (Just seeing that it's required at the end in the Conformance section, but listed as "should" in the table. That conflicts a bit...)

The data relation is required. We follow the RFC meaning of "should", which means "must".

> 3. Is a root relation type really useful in the root "catalog" / landing page? It seems to mirror self 1:1.

I kept this just to be consistent with all the other APIs. 

> 4. The items relation type should probably point to the full OGC API Features extension so that people see what "items" actually should be.

Good idea, I'll add this.

> 5. Isn't the list of endpoints missing the / endpoint (and potentially an indication on the API (e.g. /api) endpoint)?

Yes. I should check if the other conformance classes are also missing this. Agree on having service-desc endpoint also.

> 6. I'd propose to put the example into a separate file like we do it in most other cases, too. Then it could also be extended a bit with an additional collection in the current example and an additional example for the landing page.

Yes. 

> 7. The relation types mentioned in the example text (canonical, alternate representation) are not listed in any of the tables.

Yes. We're probably also missing these from STAC API - Features

> 8. The "NOTE: When this aligns with OGC API - Common it will also need to add it to the /conformance endpoint." should probably be phrased differently. It basically also applies to Features and for better OGC API compliance I'd actually add it to the top list of relation types. I don't see this is not (directly) inherited from OGC APIs while the other parts are, e.g. the API doc endpoint(s).

Okay, I'll reword this.

**Comment by m-mohr** [comment]
> I put it in pilot because it's just a subset of `STAC API - Features`. Any impl that already supports that class can just add this conformance class.

Still, the write-up here and the conformance class is new with no implementation. No OpenAPI document is available (i.e. the schmema), thus following the maturity levels it must be "Proposal" IMHO.

> The data relation is required. We follow the RFC meaning of "should", which means "must".

Which RFC is that? RFC2119 says "should" means "recommended", which is not equal to "must". 

> I kept this just to be consistent with all the other APIs.

Which other APIs?

**Comment by philvarner** [comment]
> > I put it in pilot because it's just a subset of `STAC API - Features`. Any impl that already supports that class can just add this conformance class.
> 
> Still, the write-up here and the conformance class is new with no implementation. No OpenAPI document is available (i.e. the schmema), thus following the maturity levels it must be "Proposal" IMHO.

There is an openapi.yaml in the same directory as the Collections readme spec.

> > The data relation is required. We follow the RFC meaning of "should", which means "must".
> 
> Which RFC is that? RFC2119 says "should" means "recommended", which is not equal to "must".

Sorry, I said RFC in the general sense. Specifically, from OGC API - Features Part 1:

"This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard."

> > I kept this just to be consistent with all the other APIs.
> 
> Which other APIs?

Sorry, I meant the other STAC API conformance classes.

**Comment by m-mohr** [comment]
> There is an openapi.yaml in the same directory as the Collections readme spec.

Ah, then the Readme must be updated. It says: "OpenAPI specification: Missing" - still, there's no implementation of the new conformance class yet.

> "This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard."

That text doesn't mention "should". Are you confusing "shall" and "should"? I guess the change required here is:
"The following Link relations should exist in the Landing Page (root)." => "The following Link relations shall exist in the Landing Page (root)."

It seems this issue also exists in other parts, e.g. core: https://github.com/radiantearth/stac-api-spec/tree/master/core - there it says the first table is a "should" (which is equal to recommended) and the following table says it is "recommended", which is the same so the tables could be merged in the end.

> Sorry, I meant the other STAC API conformance classes.

The other conformance classes require "root" in the root document? I only see a "should" (but that's related to the issue above). I don't think requiring a root in itself is very useful, it's just duplicating self.

**Comment by m-mohr** [comment]
See also:

![grafik](https://user-images.githubusercontent.com/8262166/129376274-edfcb6c4-fc69-448c-96b0-d74ddb402733.png)

**Comment by philvarner** [comment]
You're totally right about that, I was mixing up shall and should. I'll look to make this consistent. Though, I think OGC API uses "should" a lot when they mean shall, since it's on some items that I thought were required.

I'll update the OpenAPI missing bit.

I agree that `root` in the landing page isn't that useful, but I was just copying what we already had.

**Comment by m-mohr** [comment]
> I agree that `root` in the landing page isn't that useful, but I was just copying what we already had.

I'm wondering whether we should change that in general? I don't see any value in it...

**Comment by philvarner** [comment]
> > I agree that `root` in the landing page isn't that useful, but I was just copying what we already had.
> 
> I'm wondering whether we should change that in general? I don't see any value in it...

I feel it's a good practice to have it. It makes it straightforward to find the root from an arbitrary url, otherwise you have to continue traversing parent links until there are none.

**Comment by m-mohr** [comment]
Yes, I agree that having it is good EXCEPT for the root itself. You can easily determine that it's the root as it has no parent link, so there's no traversing of links involved.

**Comment by philvarner** [comment]
I think it should for consistency with the other resources. However, right now, this text just makes it consistent with the other 3 conformance classes, so let's address that in another PR -- I filed https://github.com/radiantearth/stac-api-spec/issues/215 to track the issue

**Comment by m-mohr** [comment]
Okay, let's follow up on #215 then.
