### ISSUE TITLE
Document Pagination Extension in the same way all other extensions are 

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#20]
Pagination extension is mentioned in root spec and in openapi, but has no entry in the extensions directory.  This is likely just reorganizing what already exists.

**Comment by matthewhanson** [comment]
Decided that this should not be an extension. Paging is part of core, and POST requests are part of core STAC API Spec, so the core should include paging for GET and POST requests.

Update language in API spec to not refer to paging as an extension
