### ISSUE TITLE
Should we allow OpenAPI 3.0 or 3.1 spec version from /api?

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#214]
OGC API Part 5 will define using OpenAPI 3.1 spec for the service-desc
https://github.com/opengeospatial/ogcapi-features/issues/404

After discussion at STAC API mtg today, I think we wait on this to see where Part 5 gets to.

**Comment by m-mohr** [comment]
Maybe not arbitrary, but maybe allow 3.0 and 3.1 (or 3.x) - OAFeat allows 3.0 in the core and is coming up with an extension for 3.1 so that seems to be a good choice, I think.

**Comment by philvarner** [comment]
I re-wrote this to specify OpenAPI 3.0 or 3.1. However, I don't think we have a good reason for *requiring* that only those two can be used, so I'm in favor using the exact same language as OAFeat, and just recommending users use either OpenAPI 3.0 or 3.1

**Comment by m-mohr** [comment]
I fully agree with you.
