### ISSUE TITLE
bbox-crs is still mentioned in core/commons.yaml

### ISSUE THREAD

**Issue by NicolaiMogensen** [radiantearth/stac-api-spec#224]
PR #64 removes all mentions of bbox-crs from core, except a descriptive text under `bbox` in `cor/commons.yaml` https://github.com/radiantearth/stac-api-spec/blob/0f1ff40964bcc12c21c89ea2701204030fad5087/core/commons.yaml#L521 

This should probably also be removed, as to not confuse users.

**Comment by philvarner** [comment]
Thanks for spotting this @NicolaiMogensen !
