### ISSUE TITLE
Consolidate numerous pagination descriptions into a single one

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#236]
We describe pagination in several different places, but it would be better to consolidate these into one and reference it from each individual conformance class.

**Comment by pieschker** [comment]
Is this done?

**Comment by philvarner** [comment]
Collections has been merged into Features, so this is no longer a duplicate.

After looking at them, I think it's more confusing to have a single description of pagination, because they're all subtly different.
