### ISSUE TITLE
Make all example URIs consistent

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#244]
Make all example URIs consistent. 

We use a mix, including the unregistered domain stacserver.org

**Comment by matthewhanson** [comment]
stac-spec is also using a mix of domains.  We used remotedata.io in the example Remote Data extension: https://github.com/stac-extensions/remote-data/blob/main/examples/item.json

**Comment by philvarner** [comment]
I'm in favor of updating all of these to be `stac-api.example.com`
