### ISSUE TITLE
Mention ItemCollection in Markdown

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-api-spec#25]
ItemCollection is being removed from core, discuss if it belongs here.

**Comment by geospatial-jeff** [comment]
I think it should be included in the api spec.  I can't come up with a better replacement for representing groups of items in `/collections/{collectionId}/items` and `/search` responses.  Having a feature collection just makes sense since items extend geojson features.

The most atomic response is just an array of stac items, but there is value in adding the extra top level fields to create a feature collection for client compatibility.

I also think keeping the top level response as an object is valuable for adding other fields (ex. context/paging extension).

**Comment by matthewhanson** [comment]
Discussed in Sprint 6, decided we don't need both JSON schema and OpenAPI.

OpenAPI docs should define the search response, closing.

**Comment by philvarner** [comment]
> Discussed in Sprint 6, decided we don't need both JSON schema and OpenAPI.
> 
> OpenAPI docs should define the search response, closing.

@matthewhanson we do need to add the markdown description of ItemCollection and the sample files, correct? I'll do this, but wanted to check before creating a PR.

**Comment by philvarner** [comment]
@matthewhanson also related to this is using https://github.com/sparkgeo/stac-validator requires JSON schema definitions, and it would be useful to be able to validate API responses using this in addition to Catalogs and Items.

**Comment by m-mohr** [comment]
OpenAPI files are basically JSON Schema with the nullable exception, but some JSON Schema validators even understand that. 

And I don't think we need a markdown description. It's described in the (rendered) OpenAPI Files, too. Also, I don't see why we would need it for that particular response, but not the others (e.g. /collections).

**Comment by cholmes** [comment]
I'm re-opening this, since I think we need at least some reference somewhere in the markdown. There are a couple references in the API spec, and it'd be weird to dump people straight into an OpenAPI document. I think it can be a brief reference, but I'd like something to link to.

**Comment by cholmes** [comment]
@m-mohr - was your thumbs down that I shouldn't include a reference in the API spec?

**Comment by m-mohr** [comment]
I think I misunderstood your point. I just think the OpenAPI file is usually enough normative information and I don't like having duplicated information, the original ItemCollection file was rather long, but maybe -to make it better linkable-, add a very short chapter here? https://github.com/radiantearth/stac-api-spec/blob/master/api-spec.md#ogc-api---features-endpoints

**Comment by m-mohr** [comment]
By the way, in #61 I had to remove all references to the itemcollection markdown file as it doesn't exist anywhere ;-)

**Comment by cholmes** [comment]
Cool. I was definitely thinking a short little paragraph. I like OpenAPI as normative, but also not making people have to wade through it to understand the spec. 

I was getting those warnings on the itemcollection markdown but for some reason it wasn't blocking CI previously. But I'll probably add them back in when I get this paragraph in.

**Comment by m-mohr** [comment]
The only thing we should do is to be consistent. While /collections is reported as only JSON, /collections/:id/items is reported as ItemCollection. Why is that? Both have specific JSON Schemas and either we should also expose /collections as "CollectionCollection" (hehe, better name?) or also just expose the other endpoint also as JSON. So if you add ItemCollection, also add CollectionCollection...

**Comment by cholmes** [comment]
Hrm, true. 

I think you've convinced me to hold off on this for beta.2, as I'd like to get beta.1 out the door, and this is more thinking than I need. I'm also semi-optimistic that OGC API - Records will have a draft and we can actually add collection search in beta.2, and then it can make sense to talk about both of them.

**Comment by m-mohr** [comment]
As discussed, we can probably just publish the latest itemcollection.md from stac-spec history and publish it with the itemCollection OpenAPI fragment in beta.1. Assigning to myself.
