### ISSUE TITLE
Require that /children must reflect the root children?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#251]
The Children conformance class says (highlighted text by me):

> It is **recommended** that the Catalog and Collection objects returned by the /children endpoint are the same as those referenced by child link relations in the STAC API Landing Page.

Why is this only recommended? For client implementations, it's much easier to implement if the links in the root landing page child links are "equal" to the /children response. Why? Let me give a short example:

STAC Browser requests/has:
- /collections (which may or may not contain what the others have)
- /children (which is allowed to contain more or fewer children than the landing page)
- landing page child and item links (which is allowed to contain more or fewer children than /children)

Now I need to merge all three sources together **and check for duplicates**, which is a pain and error-prone as some may only provide a URL and some may only provide an ID. Can we improve this situation somehow?

This get's especially annoying if I try to paginate / any or multiple of the sources have pagination in place. Like how shall I paginate something from three different sources at the same time?

**Comment by matthewhanson** [comment]
Discussed inn working session.

- children conformance class needs to require that /children includes all child links
