### ISSUE TITLE
reorganize (most?) extensions into separate repos

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#258]
Extensions should all exist in separate repos, as they will be (usually) be versioned independently.

- [] Version
- [] Transaction
- [] Fields
- [] Filter
- [] Context
- [] Query
- [] Sort

Motivating examples: 

- Filter Extension depends on CQL2, but this spec is still in draft.
- Transaction Extension is related to OGC API - Features Part 4, which is in draft.
- I don't know if any implementations support Version Extension

Others are pretty stable, so maybe should just be released with 1.0.0?: Query, Sort, Fields, Context

WIP Aggregation Extension is a good example of something that won't make 1.0.0, but would be ideal to be added later.

Others like fields and sort are pretty stable, but it would be useful to have them versioned independently in case they need to change (e.g., maybe a `/fieldable` or `/sortable` endpoint needs to be added).

Open Question - Maybe add to stac-extensions and prefix with `api-`?

**Comment by m-mohr** [comment]
Thoughts: 
- Filter outside and our "old" Query being inside the core API repo is weird
- What the status of context?
- Conformance class URIs should not change, but URIs could be virtual (do not need to resolve)
