### ISSUE TITLE
Must or should media type for links (e.g., item, next, prev, etc)?

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#275]
Currently, some of the spec says that links must have type "application/geo+json". Many omit this. These should be consistent, and it's unclear if making them a must or a should would be better.

**Comment by cholmes** [comment]
What does features api do?

**Comment by philvarner** [comment]
OAFeat says that the link **must** have a `type`, but does not explicitly what that type is. All of the examples for next and prev use `application/geo+json`. Those endpoints **must** respond to an Accept header of `application/geo+json`, and **must** set a Content-Type header of `application/geo+json`.

With those constraints, I think it's not only reasonable, but probably most correct to require the links to have `type: application/geo+json`

**Comment by philvarner** [comment]
I looked through, and if we agree that `application/geo+json` is the right type to specify, then there are no changes to make.

**Comment by cholmes** [comment]
Cool. OAFeat was meant to be super flexible, and we aligned that STAC API just focuses on JSON / GeoJSON. So agree that we should require it, and update any examples.

**Comment by philvarner** [comment]
I couldn't find any examples that needed updating, so closing.
