### ISSUE TITLE
JSON schemas for endpoints

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-api-spec#29]
/ returns a STAC catalog
/collections/{cid} returns a Collection
/collections/{cid}/items/{id} returns an Item

So those can all be validated with the schemas in stac-spec

However:
/collections
/collections/{cid}/items
/search

Don't have any schemas and so can't be validated, those should be added here.

Related to #25

**Comment by matthewhanson** [comment]
Also note that
`/collections/{cid}/items` and `/search` would have the same schema for the response.

**Comment by m-mohr** [comment]
The OpenAPI basically contains a Schema. Why not validate against the OpenAPI file?

**Comment by matthewhanson** [comment]
@m-mohr  I was wondering if that would work, but wasn't sure...can we use existing validator that you wrote? Would it validate each Item in a search response as well?

**Comment by m-mohr** [comment]
> @m-mohr I was wondering if that would work, but wasn't sure...

There are OpenAPI validators out there, we use  a Go-based one in openEO, but it seems not that easy than JSON Schema validation.

> can we use existing validator that you wrote?

No, OpenAPI Schema still slightly diverges from JSON Schema and OpenAPI has more things to be checked (e.g. headers).

> Would it validate each Item in a search response as well?

No, but a OpenAPI tool would do some checks. Issue is that the OpenAPI is not as detailed as our JSON Schemas (common metadata and extensions are missing for example), but on the other hand it would be a pain to (create and) update both JSON Schemas and OpenAPI files. In the long run we really need JSON Schema support in OpenAPI: https://apisyouwonthate.com/blog/openapi-v31-and-json-schema-2019-09

**Comment by matthewhanson** [comment]
Do not need to duplicate info in JSON Schemas and Open API. 

API will define responses in Open API docs, not JSON Schema

**Comment by m-mohr** [comment]
> @m-mohr I was wondering if that would work, but wasn't sure...can we use existing validator that you wrote? Would it validate each Item in a search response as well?

@matthewhanson Yes, it does that since today.
