### ISSUE TITLE
Transaction extension clarifications

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-api-spec#292]
A few small changes to the transaction statement based on @jonhealy1 comments on #291

#### Clarify POST body language

https://github.com/radiantearth/stac-api-spec/pull/291#discussion_r829994090

Clarify if the posted data would need to have an ID.

### Shall -> Must for creating new resource

From https://github.com/radiantearth/stac-api-spec/pull/291#discussion_r829740770

#### Clarify partial item update

Based on this comment: https://github.com/radiantearth/stac-api-spec/pull/291#discussion_r829743967

For the line in the transaction README that reads:

> May create only some of the Items in the ItemCollection.

Expand this text to describe when only some items would be created and describe recommended behavior as per Phil's linked comment.

**Comment by jonhealy1** [comment]
@lossyrob Looks great. Thanks.
