### ISSUE TITLE
Should the CQL filter fragment be removed

### ISSUE THREAD

**Issue by tschaub** [radiantearth/stac-api-spec#303]
It looks like https://github.com/radiantearth/stac-api-spec/blob/master/fragments/filter/cql.yml is out of date with respect to https://github.com/opengeospatial/ogcapi-features/blob/master/cql2/standard/schema/cql2.yml.  Should the version in this repo be removed (or updated)?

**Comment by philvarner** [comment]
It just needs to be removed -- we no longer use it and instead reference the other one.

**Comment by chiarch84** [comment]
Could you please explain me better why the CQL filter has disappeared in the 1.0.0-rc.2 APIs? Is it supposed to be superseded by a new type of filter?

**Comment by m-mohr** [comment]
Extensions have been moved to another organization, I think what you are looking for is here now:
https://github.com/stac-api-extensions/filter

**Comment by chiarch84** [comment]
thanks a lot @m-mohr I didn't know about this organization change!

**Comment by chiarch84** [comment]
which is the new Organization? I can't find anything about it.

**Comment by m-mohr** [comment]
https://github.com/stac-api-extensions
