### ISSUE TITLE
CRS handling for the `intersects` parameter

### ISSUE THREAD

**Issue by AsgerPetersen** [radiantearth/stac-api-spec#307]
Having a STAC API which supports different CRSs for input it is possible to specify the CRS of `bbox` by using `bbox-crs` and CRS of geometries in the `filter` by using `filter-crs`. 

In this context it seems inconsistent that there is no CRS support for the `intersects` parameter as the only one.

We are aware of the complexity of having multiple standards and extensions in play here, but we wanted to raise the issue as it would be great to have a standardised way to handle this instead of hacking our own.

**Comment by philvarner** [comment]
Related: https://github.com/radiantearth/stac-api-spec/issues/85
