### ISSUE TITLE
ItemCollection README.md fix

### ISSUE THREAD

**Issue by mkincyan** [radiantearth/stac-api-spec#315]
Please correct me if I'm wrong but I think there's an issue with the README.md here https://github.com/radiantearth/stac-api-spec/blob/master/fragments/itemcollection/README.md

- `features` should be documented to return `[Stac Item]`.
- `links` should be documented to return `[Link Object]`.

**Comment by mkincyan** [comment]
Note, they should both be arrays, instead of single items as currently documented.

**Comment by philvarner** [comment]
Thanks for noticing this. It's a link, so it has brackets around it in the code, but it needs an extra set to make it show them.

**Comment by philvarner** [comment]
Verified that the openapi.yaml is correctly defined as an array.

**Comment by mkincyan** [comment]
Thanks for seeing to this so quickly. I can confirm it looks correct on main now.
