### ISSUE TITLE
Make Browsable part of STAC API - Core?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#323]
After a discussion today with @philvarner, I was wondering whether the Browsable conformance class should actually be part of STAC API - Core. STAC API Core is very slim and Browsable is basically just a tiny addition says that it is potentially a static catalog (or similar). So to make a "static catalog" an "API" you'd just implement STAC API Core + Browsable. And it seems important enough to have this in a central place and not "hidden" in an extension because you should probably need to decide whether you want to add it or not in any case.

**Comment by philvarner** [comment]
I think practically, it needs to be in an extension because we have no implementations of it, so it will definitely delay release of 1.0.0. I moved it here: https://github.com/stac-api-extensions/browseable

**Comment by cholmes** [comment]
Discussed this is in STAC meeting 8/15/22, and reached consensus that we should add browseable to the core foundational specification, but just as an optional conformance class. @philvarner will update #321 to reflect this.
