### ISSUE TITLE
Different response model for Item Search GET/POST

### ISSUE THREAD

**Issue by emmanuelmathot** [radiantearth/stac-api-spec#325]
I do not understand why the response of the [POST search](https://github.com/radiantearth/stac-api-spec/blob/v1.0.0-rc.1/item-search/openapi.yaml#L90) in item-search API does not include the context extension as per [GET search](https://github.com/radiantearth/stac-api-spec/blob/v1.0.0-rc.1/item-search/openapi.yaml#L54)
If I am missing something, an explanation would be very much appreciated.

If this is a mistake, I can make a quick PR to fix it.

**Comment by emmanuelmathot** [comment]
Indeed, now context is an extension and not included in item-search API anymore. Thx.

**Comment by philvarner** [comment]
related to this, I think we'll likely be deprecating the Context extension in favor of just having the numberMatched and numberReturned fields in ItemCollection, which is the same way OAFeat does it with FeatureCollection.
