### ISSUE TITLE
Required root links

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#340]
I wasn't aware of the requirement that self and root are required for some endpoints (e.g. `/collections`). 

@philvarner has shown that self is required by OAFeat, which is fine. But root itself seems only required by some endpoints which seems inconsistent.

For example, `/search` doesn't seem to require it. Static STAC also doesn't require it. OAFeat also doesn't require it in `/collections`. I'm wondering whether it should be more consistent and only be recommended in all endpoints?

More an issue for discussion rather than a request for change. I'm not sure either yet, but would like to see this being somewhat consistent.

_Started by @m-mohr in https://github.com/radiantearth/stac-api-spec/pull/331#discussion_r992029574_

**Comment by philvarner** [comment]
related 

- #350

**Comment by philvarner** [comment]
Current status of this is:

- Core requires it on the landing page
- Features (and thereby Collections) requires it for all endpoint responses require `root`
- Item Search does not list is as a link rel, but the example has it. Planetary Computer (stac-fastapi) has it, Earth Search (stac-server) does not (but I will add it in the next release!). 

I would be in favor of adding this to Item Search.
