### ISSUE TITLE
Best way to return maximum item object for a request

### ISSUE THREAD

**Issue by LukeSturtevant** [radiantearth/stac-api-spec#348]
Hello, 

I would like to return the maximum number of item objects from the server for a given request. I'm running into an error when attempting to increase the limit parameter to the maximum 10000 granule return as described here [https://github.com/radiantearth/stac-api-spec/tree/main/item-search]. My parameter request is as follows 

{'limit': 10000,
 'bbox': '-150.178328730251,61.874156820033626,-150.0672145373403,62.338257626817665',
 'datetime': '2013-01-01T00:00:00Z/2022-10-20T23:59:59Z',
 'collections': ['HLSS30.v2.0', 'HLSL30.v2.0']}

The error I get is: requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The request seems to work for all limit values < 195 for this specific request. Is that because there are only 195 possible objects items for this request? Thank you for your help on this issue.

**Comment by philvarner** [comment]
This isn't a question about the stac api specification, but with the specific server you're trying to hit. 

My guess from your error is that the server is returning an error status code and a non-JSON value, which is why the JSON decoder is failing.
