### ISSUE TITLE
Broken link in features spec

### ISSUE THREAD

**Issue by gadomski** [radiantearth/stac-api-spec#356]
At minimum, https://github.com/radiantearth/stac-api-spec/blob/d4f8b4ab45e17e9923bd75cc58cace4819e645ff/ogcapi-features/README.md?plain=1#L22 is a broken URL. I imagine there's others, since I see similar link structures in the document.

**Comment by philvarner** [comment]
Looks like the script that publishes the openapi fails with Features and Collections. Core and Item Search work and are available.

**Comment by emmanuelmathot** [comment]
Same problem with many extensions referencing the https://api.stacspec.org/v1.0.0-rc.2/ogcapi-feature schema in release v1.0.0-rc.2

**Comment by emmanuelmathot** [comment]
@philvarner Could you add the missing schema manually in  https://api.stacspec.org ? That would solve this issue. Thx

**Comment by philvarner** [comment]
I'll see what I can do.
