### ISSUE TITLE
Conformance classes in OpenAPI schema

### ISSUE THREAD

**Issue by emmanuelmathot** [radiantearth/stac-api-spec#361]
It would be useful to have the conformance classes directly specified in the schemas. We could use it to automatically generate the landing page in the case of a STAC API framework leveraging code generation.
It would be possible to specify them at schema or operation level for a fine granularity. For instance with `item-search`:

```yaml
openapi: 3.0.3
info:
  title: STAC API - Item Search
  version: 1.0.0-rc.2
  description: >-
    This is an OpenAPI definition of the SpatioTemporal Asset Catalog API - Item Search
    specification.
  contact:
    name: STAC Specification
    url: 'http://stacspec.org'
  license:
    name: Apache License 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  conformance: [ "https://api.stacspec.org/v1.0.0-rc.2/item-search" ]
tags:
  - name: Item Search
    description: essential characteristics of a STAC API
paths:
[...]
```

**Comment by philvarner** [comment]
Additional fields have to start with `x-`. I'm adding a field with name `x-conformance-classes`.

**Comment by philvarner** [comment]
These were added to the Foundation specs. I've made a mental note to add it to the extensions (but not filed the ~8 issues against every extension that could use it)
