### ISSUE TITLE
Aggregation extension

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-api-spec#38]
In order to have APIs be browsable ( #17 ), we need to support aggregations.

Aggregation is the process of creating "summaries" for fields from the set of resulting Items from any arbitrary search.

One idea for response is to return a Collection from this endpoint, which would contain an updated summaries block.

**Comment by philvarner** [comment]
Idea: /aggregatables endpoint like /queryables

**Comment by philvarner** [comment]
Closing, since https://github.com/stac-api-extensions/aggregation exists now
