### ISSUE TITLE
Should `type` be a required field for Asset?

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#387]
OAFeat requires `type` for Links. STAC API is about to require the same for the parts that don't overlap with OAFeat in:

- #368

The question here is should STAC and/or STAC API require Asset entities to have a `type` field?

**Comment by philvarner** [comment]
I'm in favor of requiring Asset entities to have a type field in STAC API. Requiring this in STAC would mean a new release (1.1.0?), which I am also in favor of.

**Comment by philvarner** [comment]
@m-mohr

**Comment by philvarner** [comment]
Decision at  2023-Feb-13 STAC meetup was that it should not be required.

**Comment by m-mohr** [comment]
... until we go 2.0.0 and require type fields in STAC Assets and Links :-)
