### ISSUE TITLE
Move "best practices" text into separate repo

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#391]
We have a large amount of text that describes "best practices" for using or implementing STAC API that is not essential to the specification defintion. Examples of this are:

- Hierarchical Catalog Recommenations
- Implementation Recommendations

Moving this text out of the spec will allow us to modify and improve it without needing to release new spec versions.

**Comment by philvarner** [comment]
dismissing after discussion at 2023-Feb-13 STAC meetup.

**Comment by m-mohr** [comment]
PSC decision from July 2025 is to move the best practices to https://github.com/radiantearth/stac-best-practices
