### ISSUE TITLE
Suggestion of adding "text" search as default possible query parameter

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-api-spec#393]
It is true that with the Query and Filter extensions whatever query can be written in STACQL or CQL, but, I think that in this [table](https://github.com/radiantearth/stac-api-spec/tree/v1.0.0-rc.2/item-search#query-parameter-table) a simple text search should be added to the list of most used parameters.

In our case for example items have "talking" names and specific descriptions  and so being able to search by simple text is useful, in particular for basic users that would take forever to understand how to create a query in STACQL or CQL language.

**Comment by philvarner** [comment]
This won't be added to the STAC API foundation specification, but it's a great idea for an Extension. Putting this as an idea in the [Extensions Incubator](https://github.com/stac-api-extensions/incubator/issues) repo is a good idea.

**Comment by chiarch84** [comment]
@m-mohr pointed me out this: https://github.com/cedadev/stac-freetext-search
