### ISSUE TITLE
Context extension: What's the replacement?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#396]
Came up in Gitter today, but I can't open issues in the context extension so doing it here so that we can keep track:

We should give a hint in the context extension readme what the actual replacement for the context extension is.

---

Chat from Gitter:

@dirkdaems wrote:
> Hi, we recently bumped into the fact that the context API extension (https://github.com/stac-api-extensions/context/) was deprecated (https://github.com/stac-api-extensions/context/commit/47ee1d3c6c90a4011df7a81476bcc8449928c7cd). Does somebody know (1) why it was deprecated and (2) what should be used to replace it?

@m-mohr wrote:
> We should probably add a note to the README that explains what should be used instead.
> 
> Quick recap:
> 
> 1. OAFeat offers the same functionality so we aligned with them
> 2. Which means that you just use what is used in OAFeat (i.e. the fields numberMatched, numberReturned etc)

@dirkdaems wrote:
> thanks, this clarification should indeed be added to the README

**Comment by philvarner** [comment]
https://github.com/stac-api-extensions/context/issues/2
