### ISSUE TITLE
Add x-www-form-urlencoded recommendation

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#4]
In radiantearth/stac-spec#724 we agreed that it would be good to have `x-www-form-urlencoded` as a recommendation. But we decided to take it out for RC2 because it is not specified anywhere, and has no explanation as to why someone might use it.

With that text it should easily get back into the spec, but we want to get rc2 / 0.9.0 out asap.

**Comment by matthewhanson** [comment]
Talked about this in sprint #6, not convinced we really need to do this, but waiting for @philvarner to weigh in.

**Comment by m-mohr** [comment]
Closing as stale issue for now.
