### ISSUE TITLE
Rendered versions broken?!

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#409]
The rendered versions, e.g. linked to from https://github.com/radiantearth/stac-api-spec/tree/main/ogcapi-features#summary, seem to be broken. For example https://api.stacspec.org/v1.0.0-rc.2/ogcapi-features gives a 404.

**Comment by philvarner** [comment]
v1.0.0-rc.2 features and collections was broken b/c the openapi.yml files were split for the 2 conformance classes, but the build wasn't updated to account for that. It's fixed in main now -- https://api.stacspec.org/main/ogcapi-features/

**Comment by philvarner** [comment]
https://github.com/radiantearth/stac-api-spec/issues/356
