### ISSUE TITLE
Required type in links

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#413]
Opening an issue here to keep track of https://github.com/opengeospatial/ogcapi-features/issues/818

It could be that type may actually not be required for all links? It sounds like it only applies to self and alternate. As we made this change recently, I'd like to clarify what OGC APIs actually mean, because it's very inconsistent there. Any maybe, if we understood incorrectly, should revert the change?!

Somewhat related issue: https://github.com/opengeospatial/ogcapi-records/issues/178#issuecomment-1504972516

**Comment by m-mohr** [comment]
@portele answered in https://github.com/opengeospatial/ogcapi-features/issues/818#issuecomment-1505024547 and type is NOT required in OAFeat. So I think we should consider reverting the change in RC3, right? @philvarner

**Comment by philvarner** [comment]
looks like it.

**Comment by m-mohr** [comment]
By the way, the type requirement change is not in the RC3 changelog, right? We should probably add that to the RC3 changelog as it's quite fundamental change.

**Comment by philvarner** [comment]
It does appear to have been left out. I'll make that change and release rc.4 today.
