### ISSUE TITLE
What is the minimum implementation required to be considered to be STAC API compliant?

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-api-spec#42]
What is the minimum implementation required to be considered to be STAC API compliant? We don't state explicitly one way or the other. For example, implementing `/search` is optional.

**Comment by m-mohr** [comment]
I would think you either implement OAFeat and return STAC compliant responses or have / and /search implemented.

**Comment by matthewhanson** [comment]
Agree it should implement OAFeat and meet all those requirements.
Then root catalog, collections, and items should all return valid STAC metadata.

Where should we add this?

**Comment by m-mohr** [comment]
This has been pretty much answered by #60 - you need to implement the landing page, all other is optional and you can figure out what is supported by the conformance classes published on the landing page.
