### ISSUE TITLE
examples of STAC API with a dynamic catalog?

### ISSUE THREAD

**Issue by rabernat** [radiantearth/stac-api-spec#43]
Over in https://github.com/stac-utils/pystac/issues/185, I asked a question about best practices for dynamically updating STAC catalogs. I am trying to find examples of how people are using STAC as an API, with the master catalog in some other format, such as a database. Can anyone point me to any such examples? Or is everyone just using static STAC .json files to catalog their data?

**Comment by m-mohr** [comment]
I guess some of these server implementation could be useful to look at: https://stacindex.org/ecosystem?category=Server&language=

**Comment by rabernat** [comment]
Thanks a lot @m-mohr! [pygeoapi](https://docs.pygeoapi.io/en/latest/) seems a lot like what I'm looking for.
