### ISSUE TITLE
Number of items count definition in the spec

### ISSUE THREAD

**Issue by keul** [radiantearth/stac-api-spec#442]
Following a thread on the STAC chatroom on gitter.

It seems that the spec doesn't fully define a "number of items returned" value for collections, although it defines pagination.

The same _is_ defined for items instead by using `numberMatched`/`numberReturned`: https://github.com/radiantearth/stac-api-spec/blob/v1.0.0/fragments/itemcollection/README.md

I'm wondering is this can be extended to collections too in STAC spec 1.0.1 or similar.

**Comment by m-mohr** [comment]
numberMatched and numberReturned as defined for the items endpoints in STAC API - Features should probably also be ported over to STAC API - Collections for the collections endpoint.

**Comment by m-mohr** [comment]
Related to #447
