### ISSUE TITLE
pagination - how to respond for the last available page

### ISSUE THREAD

**Issue by mhogeweg** [radiantearth/stac-api-spec#446]
when responding to a search with many results, pagination provides a good solution. on the pagination specification page https://github.com/radiantearth/stac-api-spec/tree/release/v1.0.0/item-search#pagination I did not find what to do when the last page is return. Should the `"rel": "next"` link simply be omitted to signify 'there is no next page because this is the last page'?

meaning: should clients interpret the absence of `"rel": "next"` to be they reached the last page?

**Comment by m-mohr** [comment]
Yes, that's the way to go. PRs are welcome for a clarification.

**Comment by mhogeweg** [comment]
2 small PRs submitted.
