### ISSUE TITLE
Clarify BBOX format

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#47]
From @jjrom: 'The format of bbox is unclear from the specification. The astrea implementation waits for a comma separated delimiter string (i.e. lon1,lat1,lon2,lat2) while the Element84 implementation waits for an array i.e. ([lon1,lat1,lon2,lat2])'

He found that Features API is without an array, since we aiming to fully align with that I think we should use that, and make it clear.

**Comment by jisantuc** [comment]
fwiw [Franklin](https://github.com/azavea/franklin/blob/300cbf01cbf3062dad9580f3b52fb15ca3c7b73f/application/src/main/scala/com/azavea/franklin/api/schemas/package.scala#L40-L55) also assumes no array brackets for bboxes in query params

**Comment by jjrom** [comment]
Same for https://github.com/jjrom/resto - it also assumes no array brackes for bboxes in query params

**Comment by cholmes** [comment]
Am making a PR for this and it seems pretty clear. Will put in a few more warnings, but I think we mostly need to get @matthewhanson to update the element84 service.
