### ISSUE TITLE
Subscribing to an AoI

### ISSUE THREAD

**Issue by kbgg** [radiantearth/stac-api-spec#6]
It'd be nice to be able to be notified of any new items matching a specific search query. Currently the way to implement this would be to constantly poll the API and parse results to find an item which is new. Polling for updates would add unnecessary load to API servers when no new items exist. Ideally there would be a way for API consumers to subscribe to a search to only get updates when something is actually updated.

There's been talk about implementing this with webhooks, message brokers, or email. 

For email I'm thinking of more user friendly emails which wouldn't be designed to be machine readable. In my QGIS plugin it'd be nice to have researchers subscribe to a study area and get an email whenever there's a new scene available for them to download.

First there should be an endpoint which list the subscription capabilities. By hitting this endpoint you can determine which subscription methods are supported by that server and how to subscribe to a topic. For example, if your server supports an SNS topic you might list the ARN for the collections.

Second there should be a way to subscribe to the topic for a specific subscription capability. If it's a webhook or email you would have an endpoint to register for that topic. If it's SNS it wouldn't be required since the ARN to subscribe is already listed in the capabilities portion.

Very rough ideas but I think it'd be a really good nice-to-have. This could also be used in the case of alerting users when an asset has been activated and is available for download.

Feedback is very much appreciated on this.

**Comment by m-mohr** [comment]
I'm also interested in this, would likely be a good extension to the API.

**Comment by joshfix** [comment]
I also like the idea of this.  I do think we should keep this very generic and HTTP-centric, however.  I think it would be ok to provide a very specific SNS or email capability as an extension. but I think it would be more useful to simply provide a webhook capability.  This reduces implementation dependencies and doesn't tie the service to "unrelated" technologies. A   developer could create another service that listens to webhook callbacks, at which point they could put it on SNS, email it, slack it, or do whatever they want.

**Comment by jisantuc** [comment]
I'm also :+1: for webhooks here. SNS leaves the consumer with a bit of work to do before they can get the information they want and commits to AWS. SSE/websockets need a collection to stick around and a way to handle dead letters, which significantly increases architectural complexity of STAC API servers. Standing up a service to receive the webhooks _feels_ lower effort to me, especially if we can provide some kind of example service in the form of a small demo server or a one-click deploy button that matches the shapes / endpoints

**Comment by philvarner** [comment]
Moved:

- https://github.com/stac-api-extensions/incubator/issues/1
