### ISSUE TITLE
Default POST to `cql-json`

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#67]
We should make it so POST can default to cql-json. This will take some openapi work, that I'm not able to take on for beta.1

_Originally posted by @matthewhanson in https://github.com/radiantearth/stac-api-spec/pull/51#r525795773_

**Comment by m-mohr** [comment]
Fixed with https://github.com/radiantearth/stac-api-spec/pull/51/commits/8c8d15370ef90da19c509f5ecd9372375064a7ea
