### ISSUE TITLE
Consider adding itemType to STAC Collections.

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#70]
Looked into itemType a bit - I could get behind it. It's referenced more in records api, where they set it to 'records'. I could see us saying 'stac' or 'stac-item' as the itemType. You specify it in the collection response. For OGC it looks like it is just used to indicate what the items are, but I think that's mostly because they are item-centric, so I think we could just use it. 

So then the STAC Response conformance class would just indicate that some of the collections are STAC, indicated by itemType = STAC?

_Originally posted by @cholmes in https://github.com/radiantearth/stac-api-spec/issues/60#issuecomment-736144638_

**Comment by m-mohr** [comment]
I am not sure any longer this works, because if we change the itemType, it doesn't comply to OGC API Features any longer. It would be compliant to Commons, but Features would complain. I guess this is a dead-end.

**Comment by cholmes** [comment]
I think it'd still be compliant to Features API - features doesn't require itemType = features - there's no test / assertion for that afaik. It just says that features is the default itemType in the collections schema. OGC API - Records aims to be Features API compliant, and uses 'record', so seems like we just follow them.

**Comment by m-mohr** [comment]
Indeed, after checking they only define a default value, not a strict enum or const. So that could work, maybe we should ask @cportele what implications another itemType has wrt to Features compliance and tooling support?

**Comment by m-mohr** [comment]
Do we actually need this? Can't we just detect it from stac_version?

To allow mixing Feature and STAC Collections we need to do a anyOf in the openapi.yaml to actually allow it, but then I think it's enough to state that it can be detected from the presence of stac_version. No need to go beyond and add itemType: stac - or are there any advantages I'm missing?

**Comment by cholmes** [comment]
Oh yeah. That works for me. If there's a future state where OGC clients really expect / rely on itemType that we can switch. Or perhaps when STAC becomes an OGC spec it'll align better. But it doesn't feel like a really consistent & clear construct in OGC yet. 

I just wanted us to consider it ;) Also it was *your* idea :)

**Comment by m-mohr** [comment]
Yeah, it became OBE ;)
