### ISSUE TITLE
document conformsTo more

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#75]
The new conformance work is mostly complete, but we need to update the docs a bit more on the new conformsTo in the landing page. #74 is related, this came out of #27

**Comment by cholmes** [comment]
The core/README.md doc has info on this.

**Comment by m-mohr** [comment]
@cholmes We should still add some language that explains how you can derive the API version from it and that it's basically the API equivalent for stac_version and stac_extensions. If not for beta.1, then an issue would help to not forget it :-)
