### ISSUE TITLE
Update info on working with openapi

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#76]
In the core readme as well as in CONTRIBUTING.md we talk about our openapi stuff a lot.

I think that's all outdated now, so we should update this to be relevant.

**Comment by cholmes** [comment]
@matthewhanson - sounds like you'll do this in #73 But if you want me to take on any portion just let me know, I'll just need a bit of confirmation / explanation.

**Comment by m-mohr** [comment]
@cholmes Is this done?

**Comment by cholmes** [comment]
Yeah, much more scaled down, but all the invalid stuff is removed.
