### ISSUE TITLE
STAC API spec validity?

### ISSUE THREAD

**Issue by bdelliott** [radiantearth/stac-api-spec#8]
The STAC API OpenAPI definition references an external JSON schema document for the GeoJSON definitions, which is disallowed by the OpenAPI v3 spec:

From section 4.7.24.1 (http://spec.openapis.org/oas/v3.0.3#properties)

> properties - Property definitions MUST be a Schema Object and not a standard JSON Schema (inline or referenced).

The problem lines are:
- https://github.com/radiantearth/stac-spec/blob/master/api-spec/openapi/STAC.yaml#L620
- https://github.com/radiantearth/stac-spec/blob/master/api-spec/openapi/STAC.yaml#L728

I will submit a PR to add validation to the CircleCI to enforce spec validation unless someone is already doing this.

**Comment by m-mohr** [comment]
I'm currently working on spectral validation for the OpenAPI file, but the API spec repo is pretty new so thinks are just starting and the CI is not even activated yet...

**Comment by m-mohr** [comment]
Regarding the OpenAPI link issue... I agree that linking JSON Schema is not allowed as $ref, but I don't see which relation this has with the quoted definition for "pattern"?!

**Comment by m-mohr** [comment]
@bdelliott Which tool would you use? It seems that Spectral doesn't check external references...

**Comment by bdelliott** [comment]
@m-mohr Sorry, I pasted the wrong snippet.  Should make more sense now.  I was able to get validation working using swagger-cli  (https://www.npmjs.com/package/swagger-cli)

Will post an MR when I get a few mins.

**Comment by m-mohr** [comment]
Thanks! Let's see how #8 works out and then we may add swagger-cli in addition. :-)

**Comment by bdelliott** [comment]
Sounds good - my laptop just died so happy to let that one back for a bit

**Comment by m-mohr** [comment]
There are actually even more invalid things in the OpenAPI file :-(

**Comment by matthewhanson** [comment]
Discussed in sprint, goal is to
- remove external links to JSON schema
- fix minor issues

To get a basic version working, then we wait for #31

**Comment by cholmes** [comment]
@matthewhanson - can you take this one soon? Hoping for beta.1 release soon.
