### ISSUE TITLE
update changelog for big restructuring

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#83]
We merged without updating, since we wanted to get everything into master.

**Comment by cholmes** [comment]
Made an attempt on this at a0453f5

Feedback appreciated @m-mohr / @matthewhanson

**Comment by m-mohr** [comment]
I don't think it is complete, but it's a good start. It will be pretty hard to capture all changes correctly in a way it's helpful to devs as we made quite a lot of substantial changes.

**Comment by cholmes** [comment]
What else would you add? Happy to take another crack at it.

**Comment by m-mohr** [comment]
Haven't looked into details, but there's not really many infos on how to approach changes as a dev. The changelog is quite high-level about some changes and thus you actually need to dig deep into the spec versions to know how to update from 0.9 for example. @joshfix once critizised that....

**Comment by cholmes** [comment]
I'm not sure how to actually describe this set of changes without people having to look at it and dig in. I get the point, but I think that works for iterative improvements where you can just scan and see what's most relevant. With this we've changed little in how it works, but implementations are going to have to figure out what they actually conformTo, and I don't think we can communicate that in the changelog fully.
