### ISSUE TITLE
Assign code owners to extensions

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#95]
From @jisantuc on gitter:

it could be useful to assign code owners to extensions, especially since with the organization in the run-up to 1.0 it's hard to tell who's worked on something in the past: https://github.com/radiantearth/stac-api-spec/commits/master/ogcapi-features/extensions

**Comment by philvarner** [comment]
I added these where relevant when the extensions were moved to stac-api-extensions.
