### ISSUE TITLE
Add recommendation to enable CORS

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#99]
CORS helps STAC work well, API's should enable it. See https://github.com/radiantearth/stac-spec/issues/888

**Comment by philvarner** [comment]
We should recommend setting (at least) on the responses:

```
access-control-allow-origin: *
access-control-allow-methods: OPTIONS, POST, GET
access-control-allow-headers: Content-Type
```

and if Transactions is supported, also `access-control-allow-methods` Transactions PUT, PATCH, DELETE
